/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afgms;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author 00499
 */
public class MainJFrame extends javax.swing.JFrame {

    private String crlf;

    /**
     * Creates new form NewJFrame
     */
    public MainJFrame() {

        initComponents();

        // 表示を初期化
        this.buttonGroupCat1.add(this.jRadioButtonSaveCat1Paste);
        this.buttonGroupCat1.add(this.jRadioButtonSaveCat1Fork);
        this.buttonGroupCat2.add(this.jRadioButtonSaveCat2Paste);
        this.buttonGroupCat2.add(this.jRadioButtonSaveCat2Fork);
        this.buttonGroupCat3.add(this.jRadioButtonSaveCat3Paste);
        this.buttonGroupCat3.add(this.jRadioButtonSaveCat3Fork);
        this.jRadioButtonSaveCat1Fork.setSelected(true); // Cat1は基本世代管理
        this.jRadioButtonSaveCat2Paste.setSelected(true); // Cat2は基本上書き
        this.jRadioButtonSaveCat3Paste.setSelected(true); // Cat3は基本上書き

        // 改行コードを取得
        this.crlf = "\n";
        try {
            this.crlf = System.getProperty("line.separator");
        } catch (SecurityException e) {
        }
    }

    private boolean basicSauceFileCopy(String sourceDir, String copyTarget, int copyMode) { // このシステムで基本とするソースファイルのコピー
        try {
            CopyFiles copyFiles = new CopyFiles();
            copyFiles.setMainJFrame(this);
            copyFiles.copySibling(sourceDir, copyTarget, copyMode);
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            this.setMessagejTextAreaRedirectErrorStream(ex.toString());
        }
        return true;
    }

    public void printInputStreamSystemInvoke(InputStream isSystemInvoke) throws IOException {
        BufferedReader brSystemInvoke = new BufferedReader(new InputStreamReader(isSystemInvoke));
        try {
            for (;;) {
                String line = brSystemInvoke.readLine();
                if (line == null) {
                    break;
                }
                System.out.println(line);
                jTextAreaRedirectErrorStream.append(line + crlf);
            }
        } finally {
            brSystemInvoke.close();
        }
    }

    public void setMessagejTextAreaRedirectErrorStream(String msg) {
        jTextAreaRedirectErrorStream.append(msg + crlf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCat1 = new javax.swing.ButtonGroup();
        buttonGroupCat2 = new javax.swing.ButtonGroup();
        buttonGroupCat3 = new javax.swing.ButtonGroup();
        jButtonSystemDir = new javax.swing.JButton();
        jTextFieldSystemDir = new javax.swing.JTextField();
        jTextFieldSourceDir = new javax.swing.JTextField();
        jButtonSourceDir = new javax.swing.JButton();
        jTextFieldCopyTarget1 = new javax.swing.JTextField();
        jButtonCatDir1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRedirectErrorStream = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonSystemInvoke = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCopyTarget2 = new javax.swing.JTextField();
        jButtonCatDir2 = new javax.swing.JButton();
        jRadioButtonSaveCat1Paste = new javax.swing.JRadioButton();
        jRadioButtonSaveCat1Fork = new javax.swing.JRadioButton();
        jRadioButtonSaveCat2Paste = new javax.swing.JRadioButton();
        jRadioButtonSaveCat2Fork = new javax.swing.JRadioButton();
        jButtonWriteCat1 = new javax.swing.JButton();
        jButtonWriteCat2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCopyTarget3 = new javax.swing.JTextField();
        jButtonCatDir3 = new javax.swing.JButton();
        jRadioButtonSaveCat3Paste = new javax.swing.JRadioButton();
        jRadioButtonSaveCat3Fork = new javax.swing.JRadioButton();
        jButtonWriteCat3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldＩｓｓｕｅＤｉｒ = new javax.swing.JTextField();
        jButtonＩｓｓｕｅＤｉｒ = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSystemDir.setText("参　照");
        jButtonSystemDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirActionPerformed(evt);
            }
        });

        jTextFieldSourceDir.setText("被起動ファイル（ソース）は本システムで作られないので、親フォルダを別システムで作る必要がある。");

        jButtonSourceDir.setText("参　照");
        jButtonSourceDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSourceDirActionPerformed(evt);
            }
        });

        jTextFieldCopyTarget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCopyTarget1ActionPerformed(evt);
            }
        });

        jButtonCatDir1.setText("参　照");
        jButtonCatDir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCatDir1ActionPerformed(evt);
            }
        });

        jTextAreaRedirectErrorStream.setColumns(20);
        jTextAreaRedirectErrorStream.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRedirectErrorStream);

        jButton4.setText("構成保存");

        jButton5.setText("構成削除");

        jButtonSystemInvoke.setText("起　動");
        jButtonSystemInvoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemInvokeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("システム");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("ソース");

        jLabel3.setText("退避　１");

        jLabel4.setText("退避　２");

        jButtonCatDir2.setText("参　照");

        jRadioButtonSaveCat1Paste.setText("無世代");

        jRadioButtonSaveCat1Fork.setText("世代増");
        jRadioButtonSaveCat1Fork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaveCat1ForkActionPerformed(evt);
            }
        });

        jRadioButtonSaveCat2Paste.setText("無世代");
        jRadioButtonSaveCat2Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaveCat2PasteActionPerformed(evt);
            }
        });

        jRadioButtonSaveCat2Fork.setText("世代増");

        jButtonWriteCat1.setText("手動書込");
        jButtonWriteCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteCat1ActionPerformed(evt);
            }
        });

        jButtonWriteCat2.setText("手動書込");
        jButtonWriteCat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteCat2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("間　　隔");

        jLabel6.setText("分");

        jLabel7.setText("クリック位置");

        jLabel8.setText("横（X)");

        jTextField5.setText("jTextField5");

        jLabel9.setText("縦（Y)");

        jTextField6.setText("jTextField6");

        jLabel10.setText("打　鍵");

        jTextField7.setText("jTextField7");

        jLabel11.setText("定期実行");

        jLabel12.setText("前置パラメタ");

        jLabel13.setText("後置パラメタ");

        jTextField1.setText("jTextField1");

        jTextField8.setText("jTextField8");

        jLabel14.setText("退避　２");

        jButtonCatDir3.setText("参　照");

        jRadioButtonSaveCat3Paste.setText("無世代");
        jRadioButtonSaveCat3Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaveCat3PasteActionPerformed(evt);
            }
        });

        jRadioButtonSaveCat3Fork.setText("世代増");

        jButtonWriteCat3.setText("手動書込");
        jButtonWriteCat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteCat3ActionPerformed(evt);
            }
        });

        jLabel15.setText("送出準備");

        jButtonＩｓｓｕｅＤｉｒ.setText("・・・");

        jTextField3.setText("jTextField3");

        jLabel16.setText("フォルダ名付加文");

        jButton1.setText("送出分岐");

        jLabel17.setText("資源格納");

        jTextField2.setText("jTextField2");

        jButton2.setText("作成");

        jButton3.setText("資源格納場所をクリップボードへコピー");

        jButton6.setText("...");

        jButton7.setText("親フォルダをクリップボードにコピー");

        jCheckBox1.setText("起動前保存");

        jCheckBox2.setText("起動後保存");

        jCheckBox3.setText("起動前保存");

        jCheckBox4.setText("起動後保存");

        jCheckBox5.setText("起動前保存");

        jCheckBox6.setText("起動後保存");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCopyTarget2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCopyTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCopyTarget3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCatDir3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSaveCat3Paste)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSaveCat3Fork)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonWriteCat3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCatDir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCatDir2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSaveCat1Paste)
                                    .addComponent(jRadioButtonSaveCat2Paste))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSaveCat2Fork)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSaveCat1Fork)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonWriteCat1)
                                    .addComponent(jButtonWriteCat2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jButtonSystemInvoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldSystemDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSystemDir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldSourceDir, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSourceDir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(2, 2, 2)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldＩｓｓｕｅＤｉｒ, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonＩｓｓｕｅＤｉｒ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addGap(91, 91, 91)
                                        .addComponent(jButton5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSystemDir)
                    .addComponent(jTextFieldSystemDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSourceDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSourceDir)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldＩｓｓｕｅＤｉｒ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonＩｓｓｕｅＤｉｒ)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCopyTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonSaveCat1Paste)
                    .addComponent(jRadioButtonSaveCat1Fork)
                    .addComponent(jButtonCatDir1)
                    .addComponent(jButtonWriteCat1)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox3)
                        .addComponent(jCheckBox4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCopyTarget2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCatDir2)
                        .addComponent(jRadioButtonSaveCat2Paste)
                        .addComponent(jRadioButtonSaveCat2Fork)
                        .addComponent(jButtonWriteCat2)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonSaveCat3Paste)
                        .addComponent(jRadioButtonSaveCat3Fork))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldCopyTarget3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCatDir3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6))
                        .addComponent(jButtonWriteCat3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(68, 68, 68)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSystemInvoke)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonWriteCat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteCat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteCat2ActionPerformed

    private void jRadioButtonSaveCat1ForkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaveCat1ForkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaveCat1ForkActionPerformed

    private void jRadioButtonSaveCat2PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaveCat2PasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaveCat2PasteActionPerformed

    private void jButtonSystemDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDir = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDir.setText(fileSystemDir.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirActionPerformed

    private void jButtonSourceDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSourceDirActionPerformed
        JFileChooser filechooserSourceDir = new JFileChooser();
        int selected = filechooserSourceDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSourceDir = filechooserSourceDir.getSelectedFile();
            this.jTextFieldSourceDir.setText(fileSourceDir.getPath());
        }
    }//GEN-LAST:event_jButtonSourceDirActionPerformed

    private void jButtonSystemInvokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemInvokeActionPerformed
        SystemInvokeThread systemInvokeThread = new SystemInvokeThread();
        systemInvokeThread.setMainJFrame(this);
        systemInvokeThread.setSystemDir(this.jTextFieldSystemDir.getText());
        systemInvokeThread.setSourceDir(this.jTextFieldSourceDir.getText());
        systemInvokeThread.start();
    }//GEN-LAST:event_jButtonSystemInvokeActionPerformed

    private void jButtonCatDir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCatDir1ActionPerformed
        JFileChooser filechooserCatDir1 = new JFileChooser();
        filechooserCatDir1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selected = filechooserCatDir1.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileCatDir1 = filechooserCatDir1.getSelectedFile();
            this.jTextFieldCopyTarget1.setText(fileCatDir1.getPath());
        }
    }//GEN-LAST:event_jButtonCatDir1ActionPerformed

    private void jButtonWriteCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteCat1ActionPerformed
        int copyMode = CopyFiles.COPY_FORK; // 世代分離のほうが安全そうなので
        if (this.jRadioButtonSaveCat1Paste.isSelected()) { // 上書きの場合
            copyMode = CopyFiles.COPY_PASTE;
        } else if (this.jRadioButtonSaveCat1Fork.isSelected()) { // 世代分離コピーの場合
            copyMode = CopyFiles.COPY_FORK;
        }
        this.basicSauceFileCopy(
                this.jTextFieldSourceDir.getText(), this.jTextFieldCopyTarget1.getText(), copyMode);
    }//GEN-LAST:event_jButtonWriteCat1ActionPerformed

    private void jTextFieldCopyTarget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCopyTarget1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCopyTarget1ActionPerformed

    private void jRadioButtonSaveCat3PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaveCat3PasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaveCat3PasteActionPerformed

    private void jButtonWriteCat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteCat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteCat3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCat1;
    private javax.swing.ButtonGroup buttonGroupCat2;
    private javax.swing.ButtonGroup buttonGroupCat3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonCatDir1;
    private javax.swing.JButton jButtonCatDir2;
    private javax.swing.JButton jButtonCatDir3;
    private javax.swing.JButton jButtonSourceDir;
    private javax.swing.JButton jButtonSystemDir;
    private javax.swing.JButton jButtonSystemInvoke;
    private javax.swing.JButton jButtonWriteCat1;
    private javax.swing.JButton jButtonWriteCat2;
    private javax.swing.JButton jButtonWriteCat3;
    private javax.swing.JButton jButtonＩｓｓｕｅＤｉｒ;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonSaveCat1Fork;
    private javax.swing.JRadioButton jRadioButtonSaveCat1Paste;
    private javax.swing.JRadioButton jRadioButtonSaveCat2Fork;
    private javax.swing.JRadioButton jRadioButtonSaveCat2Paste;
    private javax.swing.JRadioButton jRadioButtonSaveCat3Fork;
    private javax.swing.JRadioButton jRadioButtonSaveCat3Paste;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRedirectErrorStream;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldCopyTarget1;
    private javax.swing.JTextField jTextFieldCopyTarget2;
    private javax.swing.JTextField jTextFieldCopyTarget3;
    private javax.swing.JTextField jTextFieldSourceDir;
    private javax.swing.JTextField jTextFieldSystemDir;
    private javax.swing.JTextField jTextFieldＩｓｓｕｅＤｉｒ;
    // End of variables declaration//GEN-END:variables

}
