/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afgms;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import localIO.ConfigurationXML;
import testMaking.ConnectionRegsys;

/**
 *
 * @author 00499
 */
public class MainJFrame extends javax.swing.JFrame {

    private String crlf;

    private boolean isShowedSysPanel = false;
    DefaultListModel appTitlesModel = new DefaultListModel(); // appInfo で使用するリストのモデル

    static final String URL = "jdbc:mysql://localhost:3306/test_swing_jdbc?zeroDateTimeBehavior=convertToNull";
    //static final String URL = "jdbc:mysql://49.212.131.91:3306/test_swing_jdbc?zeroDateTimeBehavior=convertToNull";

    static final String USERNAME = "root";
    static final String PASSWORD = "pass";

    /**
     * Creates new form NewJFrame
     */
    public MainJFrame() {

        initComponents();

        // 表示を初期化
        this.buttonGroupCat1.add(this.jRadioButtonSaveCat1Paste);
        this.buttonGroupCat1.add(this.jRadioButtonSaveCat1Fork);
        this.buttonGroupCat2.add(this.jRadioButtonSaveCat2Paste);
        this.buttonGroupCat2.add(this.jRadioButtonSaveCat2Fork);
        this.buttonGroupCat3.add(this.jRadioButtonSaveCat3Paste);
        this.buttonGroupCat3.add(this.jRadioButtonSaveCat3Fork);
        this.jRadioButtonSaveCat1Fork.setSelected(true); // Cat1は基本世代管理
        this.jRadioButtonSaveCat2Paste.setSelected(true); // Cat2は基本上書き
        this.jRadioButtonSaveCat3Paste.setSelected(true); // Cat3は基本上書き

        // 改行コードを取得
        this.crlf = "\n";
        try {
            this.crlf = System.getProperty("line.separator");
        } catch (SecurityException e) {
        }
    }

    private boolean basicSauceFileCopy(String sourceDir, String copyTarget, int copyMode) { // このシステムで基本とするソースファイルのコピー
        try {
            CopyFiles copyFiles = new CopyFiles();
            copyFiles.setMainJFrame(this);
            copyFiles.copySibling(sourceDir, copyTarget, copyMode);
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            this.setMessagejTextAreaRedirectErrorStream(ex.toString());
        }
        return true;
    }

    public void printInputStreamSystemInvoke(InputStream isSystemInvoke) throws IOException {
        BufferedReader brSystemInvoke = new BufferedReader(new InputStreamReader(isSystemInvoke));
        try {
            for (;;) {
                String line = brSystemInvoke.readLine();
                if (line == null) {
                    break;
                }
                System.out.println(line);
                jTextAreaRedirectErrorStream.append(line + crlf);
            }
        } finally {
            brSystemInvoke.close();
        }
    }

    public void setMessagejTextAreaRedirectErrorStream(String msg) {
        jTextAreaRedirectErrorStream.append(msg + crlf);
    }

    private class AppInfo { // アプリ情報

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCat1 = new javax.swing.ButtonGroup();
        buttonGroupCat2 = new javax.swing.ButtonGroup();
        buttonGroupCat3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelExeSys = new javax.swing.JPanel();
        jLabelSeq1 = new javax.swing.JLabel();
        jButtonSystemDirSeq1 = new javax.swing.JButton();
        jTextFieldSystemDirSeq1 = new javax.swing.JTextField();
        jTextFieldSeq1 = new javax.swing.JTextField();
        jLabelSeq4 = new javax.swing.JLabel();
        jTextFieldSeq2 = new javax.swing.JTextField();
        jTextFieldSystemDirSeq2 = new javax.swing.JTextField();
        jTextFieldSeq3 = new javax.swing.JTextField();
        jLabelSeq5 = new javax.swing.JLabel();
        jTextFieldSystemDirSeq3 = new javax.swing.JTextField();
        jLabelSeq6 = new javax.swing.JLabel();
        jTextFieldSystemDirSeq4 = new javax.swing.JTextField();
        jTextFieldSeq4 = new javax.swing.JTextField();
        jLabelSeq7 = new javax.swing.JLabel();
        jTextFieldSystemDirSeq5 = new javax.swing.JTextField();
        jTextFieldSeq5 = new javax.swing.JTextField();
        jLabelSeq8 = new javax.swing.JLabel();
        jTextFieldSeq6 = new javax.swing.JTextField();
        jTextFieldSystemDirSeq6 = new javax.swing.JTextField();
        jLabelSeq9 = new javax.swing.JLabel();
        jTextFieldSystemDirSeq7 = new javax.swing.JTextField();
        jTextFieldSeq7 = new javax.swing.JTextField();
        jTextFieldSeq8 = new javax.swing.JTextField();
        jLabelSeq10 = new javax.swing.JLabel();
        jTextFieldSystemDirSeq8 = new javax.swing.JTextField();
        jLabelSeq11 = new javax.swing.JLabel();
        jTextFieldSeq9 = new javax.swing.JTextField();
        jTextFieldSystemDirSeq9 = new javax.swing.JTextField();
        jLabelSeq12 = new javax.swing.JLabel();
        jTextFieldSeq10 = new javax.swing.JTextField();
        jTextFieldSystemDirSeq10 = new javax.swing.JTextField();
        jButtonSystemDirSeq2 = new javax.swing.JButton();
        jButtonSystemDirSeq3 = new javax.swing.JButton();
        jButtonSystemDirSeq4 = new javax.swing.JButton();
        jButtonSystemDirSeq5 = new javax.swing.JButton();
        jButtonSystemDirSeq6 = new javax.swing.JButton();
        jButtonSystemDirSeq7 = new javax.swing.JButton();
        jButtonSystemDirSeq8 = new javax.swing.JButton();
        jButtonSystemDirSeq9 = new javax.swing.JButton();
        jButtonSystemDirSeq10 = new javax.swing.JButton();
        jButtonEnter = new javax.swing.JButton();
        jPanelConfig = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonSaveCat3Paste = new javax.swing.JRadioButton();
        jRadioButtonSaveCat3Fork = new javax.swing.JRadioButton();
        jButtonWriteCat3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldIssueDir = new javax.swing.JTextField();
        jButtonIssueDir = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonSystemInvoke = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBoxMakeCode = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCopyTarget2 = new javax.swing.JTextField();
        jButtonCatDir2 = new javax.swing.JButton();
        jButtonSystemDir = new javax.swing.JButton();
        jTextFieldSystemDir = new javax.swing.JTextField();
        jTextFieldSourceDir = new javax.swing.JTextField();
        jButtonSourceDir = new javax.swing.JButton();
        jTextFieldCopyTarget1 = new javax.swing.JTextField();
        jButtonCatDir1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRedirectErrorStream = new javax.swing.JTextArea();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jRadioButtonSaveCat1Paste = new javax.swing.JRadioButton();
        jCheckBox6 = new javax.swing.JCheckBox();
        jRadioButtonSaveCat1Fork = new javax.swing.JRadioButton();
        jCheckBox7 = new javax.swing.JCheckBox();
        jRadioButtonSaveCat2Paste = new javax.swing.JRadioButton();
        jButtonEnterItems = new javax.swing.JButton();
        jRadioButtonSaveCat2Fork = new javax.swing.JRadioButton();
        jButtonDeleteItems = new javax.swing.JButton();
        jButtonWriteCat1 = new javax.swing.JButton();
        jButtonSetDefaultItems = new javax.swing.JButton();
        jButtonWriteCat2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCopyTarget3 = new javax.swing.JTextField();
        jButtonCatDir3 = new javax.swing.JButton();
        jPanelAppInfo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTitles = new javax.swing.JList();
        jButtonDelete = new javax.swing.JButton();
        jButtonEntry = new javax.swing.JButton();
        jTextFieldTitle = new javax.swing.JTextField();
        jCheckBoxNewState = new javax.swing.JCheckBox();
        jTextFieldSysdir = new javax.swing.JTextField();
        jButtonSysdir = new javax.swing.JButton();
        jTextFieldExtension = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaRemark = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanelExeSys.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelExeSysFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanelExeSysFocusLost(evt);
            }
        });
        jPanelExeSys.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanelExeSysComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelExeSysComponentShown(evt);
            }
        });

        jLabelSeq1.setText("１");

        jButtonSystemDirSeq1.setText("参　照");
        jButtonSystemDirSeq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq1ActionPerformed(evt);
            }
        });

        jLabelSeq4.setText("２");

        jLabelSeq5.setText("３");

        jLabelSeq6.setText("４");

        jLabelSeq7.setText("５");

        jLabelSeq8.setText("６");

        jLabelSeq9.setText("７");

        jLabelSeq10.setText("８");

        jLabelSeq11.setText("９");

        jLabelSeq12.setText("10");

        jButtonSystemDirSeq2.setText("参　照");
        jButtonSystemDirSeq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq2ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq3.setText("参　照");
        jButtonSystemDirSeq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq3ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq4.setText("参　照");
        jButtonSystemDirSeq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq4ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq5.setText("参　照");
        jButtonSystemDirSeq5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq5ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq6.setText("参　照");
        jButtonSystemDirSeq6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq6ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq7.setText("参　照");
        jButtonSystemDirSeq7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq7ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq8.setText("参　照");
        jButtonSystemDirSeq8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq8ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq9.setText("参　照");
        jButtonSystemDirSeq9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq9ActionPerformed(evt);
            }
        });

        jButtonSystemDirSeq10.setText("参　照");
        jButtonSystemDirSeq10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirSeq10ActionPerformed(evt);
            }
        });

        jButtonEnter.setText("適　　用");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelExeSysLayout = new javax.swing.GroupLayout(jPanelExeSys);
        jPanelExeSys.setLayout(jPanelExeSysLayout);
        jPanelExeSysLayout.setHorizontalGroup(
            jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExeSysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelExeSysLayout.createSequentialGroup()
                        .addComponent(jLabelSeq4)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldSeq2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSystemDirSeq2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSystemDirSeq2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelExeSysLayout.createSequentialGroup()
                        .addComponent(jLabelSeq1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSeq1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSystemDirSeq1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSystemDirSeq1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelExeSysLayout.createSequentialGroup()
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExeSysLayout.createSequentialGroup()
                                .addComponent(jLabelSeq5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSeq3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSystemDirSeq3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelExeSysLayout.createSequentialGroup()
                                .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelExeSysLayout.createSequentialGroup()
                                        .addComponent(jLabelSeq6)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextFieldSeq4))
                                    .addGroup(jPanelExeSysLayout.createSequentialGroup()
                                        .addComponent(jLabelSeq7)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextFieldSeq5))
                                    .addGroup(jPanelExeSysLayout.createSequentialGroup()
                                        .addComponent(jLabelSeq8)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextFieldSeq6))
                                    .addGroup(jPanelExeSysLayout.createSequentialGroup()
                                        .addComponent(jLabelSeq9)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextFieldSeq7))
                                    .addGroup(jPanelExeSysLayout.createSequentialGroup()
                                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSeq10)
                                            .addComponent(jLabelSeq11)
                                            .addComponent(jLabelSeq12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldSeq10)
                                            .addComponent(jTextFieldSeq8)
                                            .addComponent(jTextFieldSeq9))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSystemDirSeq4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSystemDirSeq5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSystemDirSeq6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSystemDirSeq7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSystemDirSeq8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSystemDirSeq9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSystemDirSeq10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSystemDirSeq4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSystemDirSeq5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSystemDirSeq3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSystemDirSeq6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSystemDirSeq7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSystemDirSeq8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSystemDirSeq9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSystemDirSeq10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(378, 378, 378))
        );
        jPanelExeSysLayout.setVerticalGroup(
            jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExeSysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeq1)
                    .addComponent(jButtonSystemDirSeq1)
                    .addComponent(jTextFieldSystemDirSeq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSeq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelExeSysLayout.createSequentialGroup()
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq2)
                            .addComponent(jTextFieldSystemDirSeq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq3)
                            .addComponent(jTextFieldSystemDirSeq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq4)
                            .addComponent(jTextFieldSystemDirSeq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq5)
                            .addComponent(jTextFieldSystemDirSeq5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq6)
                            .addComponent(jTextFieldSystemDirSeq6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq7)
                            .addComponent(jTextFieldSystemDirSeq7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq8)
                            .addComponent(jTextFieldSystemDirSeq8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq9)
                            .addComponent(jTextFieldSystemDirSeq9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSeq9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSeq11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSystemDirSeq10)
                            .addComponent(jTextFieldSystemDirSeq10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelExeSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSeq12)
                        .addComponent(jTextFieldSeq10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonEnter)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("実行SYS", jPanelExeSys);

        javax.swing.GroupLayout jPanelConfigLayout = new javax.swing.GroupLayout(jPanelConfig);
        jPanelConfig.setLayout(jPanelConfigLayout);
        jPanelConfigLayout.setHorizontalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1489, Short.MAX_VALUE)
        );
        jPanelConfigLayout.setVerticalGroup(
            jPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("環境設定", jPanelConfig);

        jLabel19.setText("Vessel");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton9.setText("jButton9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 1418, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("基幹情報", jPanel1);

        jRadioButtonSaveCat3Paste.setText("無世代");
        jRadioButtonSaveCat3Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaveCat3PasteActionPerformed(evt);
            }
        });

        jRadioButtonSaveCat3Fork.setText("世代増");

        jButtonWriteCat3.setText("手動書込");
        jButtonWriteCat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteCat3ActionPerformed(evt);
            }
        });

        jLabel15.setText("送出準備");

        jButtonIssueDir.setText("・・・");

        jTextField3.setText("jTextField3");

        jLabel16.setText("フォルダ名付加文");

        jButton1.setText("（終了後に？）送出分岐");

        jLabel17.setText("資源格納");

        jButton4.setText("構成保存");

        jTextField2.setText("jTextField2");

        jButton5.setText("構成削除");

        jButton2.setText("作成");

        jButtonSystemInvoke.setText("起　動");
        jButtonSystemInvoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemInvokeActionPerformed(evt);
            }
        });

        jButton3.setText("資源格納場所をクリップボードへコピー");

        jComboBoxMakeCode.setEditable(true);
        jComboBoxMakeCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton6.setText("...");

        jLabel1.setText("システム");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton7.setText("親フォルダをクリップボードにコピー");

        jLabel2.setText("ソース");

        jCheckBox1.setText("起動前保存");

        jLabel3.setText("退避　１");

        jLabel4.setText("退避　２");

        jButtonCatDir2.setText("参　照");

        jButtonSystemDir.setText("参　照");
        jButtonSystemDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSystemDirActionPerformed(evt);
            }
        });

        jTextFieldSourceDir.setText("フォルダーは存在しない場合はダイアログを出して作成するかどうかユーザに選択させる。");

        jButtonSourceDir.setText("参　照");
        jButtonSourceDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSourceDirActionPerformed(evt);
            }
        });

        jTextFieldCopyTarget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCopyTarget1ActionPerformed(evt);
            }
        });

        jButtonCatDir1.setText("参　照");
        jButtonCatDir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCatDir1ActionPerformed(evt);
            }
        });

        jTextAreaRedirectErrorStream.setColumns(20);
        jTextAreaRedirectErrorStream.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRedirectErrorStream);

        jCheckBox2.setText("起動後保存");

        jCheckBox3.setText("起動前保存");

        jCheckBox4.setText("起動後保存");

        jCheckBox5.setText("起動前保存");

        jRadioButtonSaveCat1Paste.setText("無世代");

        jCheckBox6.setText("起動後保存");

        jRadioButtonSaveCat1Fork.setText("世代増");
        jRadioButtonSaveCat1Fork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaveCat1ForkActionPerformed(evt);
            }
        });

        jCheckBox7.setText("編集可否");

        jRadioButtonSaveCat2Paste.setText("無世代");
        jRadioButtonSaveCat2Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaveCat2PasteActionPerformed(evt);
            }
        });

        jButtonEnterItems.setText("ENT");

        jRadioButtonSaveCat2Fork.setText("世代増");

        jButtonDeleteItems.setText("削除");

        jButtonWriteCat1.setText("手動書込");
        jButtonWriteCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteCat1ActionPerformed(evt);
            }
        });

        jButtonSetDefaultItems.setText("新規");

        jButtonWriteCat2.setText("手動書込");
        jButtonWriteCat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteCat2ActionPerformed(evt);
            }
        });

        jTextField4.setText("ABCD12345");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("間　　隔");

        jLabel6.setText("分");

        jLabel7.setText("クリック位置");

        jLabel18.setText("作成フォルダ名");

        jButton8.setText("Dir作成移動（不要？）");

        jLabel8.setText("横（X)");

        jTextField5.setText("jTextField5");

        jLabel9.setText("縦（Y)");

        jTextField6.setText("jTextField6");

        jLabel10.setText("打　鍵");

        jTextField7.setText("jTextField7");

        jLabel11.setText("定期実行");

        jLabel12.setText("前置パラメタ");

        jLabel13.setText("後置パラメタ");

        jTextField1.setText("jTextField1");

        jTextField8.setText("jTextField8");

        jLabel14.setText("退避　２");

        jButtonCatDir3.setText("参　照");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCopyTarget2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCopyTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCopyTarget3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonCatDir3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSaveCat3Paste)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonSaveCat3Fork)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonWriteCat3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCatDir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCatDir2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSaveCat1Paste)
                                    .addComponent(jRadioButtonSaveCat2Paste))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSaveCat2Fork)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox4))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSaveCat1Fork)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonWriteCat1)
                                    .addComponent(jButtonWriteCat2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jButtonSystemInvoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addGap(91, 91, 91)
                                        .addComponent(jButton5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldSystemDir)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextFieldSourceDir, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonSourceDir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonSystemDir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldIssueDir, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonIssueDir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxMakeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEnterItems)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteItems)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSetDefaultItems)))
                        .addGap(236, 236, 236)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMakeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox7)
                    .addComponent(jButtonEnterItems)
                    .addComponent(jButtonDeleteItems)
                    .addComponent(jButtonSetDefaultItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSystemDir)
                    .addComponent(jTextFieldSystemDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSourceDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSourceDir)
                    .addComponent(jLabel2)
                    .addComponent(jButton7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldIssueDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIssueDir)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCopyTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonSaveCat1Paste)
                    .addComponent(jRadioButtonSaveCat1Fork)
                    .addComponent(jButtonCatDir1)
                    .addComponent(jButtonWriteCat1)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox3)
                        .addComponent(jCheckBox4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCopyTarget2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCatDir2)
                        .addComponent(jRadioButtonSaveCat2Paste)
                        .addComponent(jRadioButtonSaveCat2Fork)
                        .addComponent(jButtonWriteCat2)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonSaveCat3Paste)
                        .addComponent(jRadioButtonSaveCat3Fork))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldCopyTarget3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCatDir3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6))
                        .addComponent(jButtonWriteCat3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSystemInvoke)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jListTitles.setModel(appTitlesModel);
        jListTitles.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jListTitlesFocusGained(evt);
            }
        });
        jListTitles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTitlesValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListTitles);

        jButtonDelete.setText("　　削除　　");

        jButtonEntry.setText("設定の保存");

        jTextFieldTitle.setText("jTextField10");

        jCheckBoxNewState.setText("新しい設定を作成する");

        jTextFieldSysdir.setText("jTextField11");

        jButtonSysdir.setText("…");
        jButtonSysdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSysdirActionPerformed(evt);
            }
        });

        jTextFieldExtension.setText("jTextField12");

        jTextAreaRemark.setColumns(20);
        jTextAreaRemark.setRows(5);
        jScrollPane4.setViewportView(jTextAreaRemark);

        javax.swing.GroupLayout jPanelAppInfoLayout = new javax.swing.GroupLayout(jPanelAppInfo);
        jPanelAppInfo.setLayout(jPanelAppInfoLayout);
        jPanelAppInfoLayout.setHorizontalGroup(
            jPanelAppInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAppInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxNewState, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAppInfoLayout.createSequentialGroup()
                        .addGroup(jPanelAppInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAppInfoLayout.createSequentialGroup()
                                .addComponent(jTextFieldSysdir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSysdir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelAppInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAppInfoLayout.createSequentialGroup()
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(jButtonEntry))))
                .addGap(891, 891, 891))
        );
        jPanelAppInfoLayout.setVerticalGroup(
            jPanelAppInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAppInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAppInfoLayout.createSequentialGroup()
                        .addComponent(jButtonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEntry))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxNewState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAppInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSysdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSysdir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("アプリ情報設定", jPanelAppInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonWriteCat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteCat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteCat2ActionPerformed

    private void jButtonWriteCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteCat1ActionPerformed
        int copyMode = CopyFiles.COPY_FORK; // 世代分離のほうが安全そうなので
        if (this.jRadioButtonSaveCat1Paste.isSelected()) { // 上書きの場合
            copyMode = CopyFiles.COPY_PASTE;
        } else if (this.jRadioButtonSaveCat1Fork.isSelected()) { // 世代分離コピーの場合
            copyMode = CopyFiles.COPY_FORK;
        }
        this.basicSauceFileCopy(
                this.jTextFieldSourceDir.getText(), this.jTextFieldCopyTarget1.getText(), copyMode);
    }//GEN-LAST:event_jButtonWriteCat1ActionPerformed

    private void jRadioButtonSaveCat2PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaveCat2PasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaveCat2PasteActionPerformed

    private void jRadioButtonSaveCat1ForkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaveCat1ForkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaveCat1ForkActionPerformed

    private void jButtonCatDir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCatDir1ActionPerformed
        JFileChooser filechooserCatDir1 = new JFileChooser();
        filechooserCatDir1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selected = filechooserCatDir1.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileCatDir1 = filechooserCatDir1.getSelectedFile();
            this.jTextFieldCopyTarget1.setText(fileCatDir1.getPath());
        }
    }//GEN-LAST:event_jButtonCatDir1ActionPerformed

    private void jTextFieldCopyTarget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCopyTarget1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCopyTarget1ActionPerformed

    private void jButtonSourceDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSourceDirActionPerformed
        JFileChooser filechooserSourceDir = new JFileChooser();
        int selected = filechooserSourceDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSourceDir = filechooserSourceDir.getSelectedFile();
            this.jTextFieldSourceDir.setText(fileSourceDir.getPath());
        }
    }//GEN-LAST:event_jButtonSourceDirActionPerformed

    private void jButtonSystemDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDir = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDir.setText(fileSystemDir.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirActionPerformed

    private void jButtonSystemInvokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemInvokeActionPerformed
        SystemInvokeThread systemInvokeThread = new SystemInvokeThread();
        systemInvokeThread.setMainJFrame(this);
        systemInvokeThread.setSystemDir(this.jTextFieldSystemDir.getText());
        systemInvokeThread.setSourceDir(this.jTextFieldSourceDir.getText());
        systemInvokeThread.start();
    }//GEN-LAST:event_jButtonSystemInvokeActionPerformed

    private void jButtonWriteCat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteCat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWriteCat3ActionPerformed

    private void jRadioButtonSaveCat3PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaveCat3PasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaveCat3PasteActionPerformed

    private void jButtonSystemDirSeq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq1ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq1 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq1.setText(fileSystemDirSeq1.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq1ActionPerformed

    private void jButtonSystemDirSeq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq2ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq2 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq2.setText(fileSystemDirSeq2.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq2ActionPerformed

    private void jButtonSystemDirSeq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq3ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq3 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq3.setText(fileSystemDirSeq3.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq3ActionPerformed

    private void jButtonSystemDirSeq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq4ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq4 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq4.setText(fileSystemDirSeq4.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq4ActionPerformed

    private void jButtonSystemDirSeq5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq5ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq5 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq5.setText(fileSystemDirSeq5.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq5ActionPerformed

    private void jButtonSystemDirSeq6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq6ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq6 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq6.setText(fileSystemDirSeq6.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq6ActionPerformed

    private void jButtonSystemDirSeq7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq7ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq7 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq7.setText(fileSystemDirSeq7.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq7ActionPerformed

    private void jButtonSystemDirSeq8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq8ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq8 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq8.setText(fileSystemDirSeq8.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq8ActionPerformed

    private void jButtonSystemDirSeq9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq9ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq9 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq9.setText(fileSystemDirSeq9.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq9ActionPerformed

    private void jButtonSystemDirSeq10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSystemDirSeq10ActionPerformed
        JFileChooser filechooserSystemDir = new JFileChooser();
        int selected = filechooserSystemDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileSystemDirSeq10 = filechooserSystemDir.getSelectedFile();
            this.jTextFieldSystemDirSeq10.setText(fileSystemDirSeq10.getPath());
        }
    }//GEN-LAST:event_jButtonSystemDirSeq10ActionPerformed

    private void storeItems() {
        ConfigurationXML conf = new ConfigurationXML("ExecutionSys.XML"); //ファイルの位置は再考する

        conf.upDateProperty("jTextFieldSeq1", this.jTextFieldSeq1.getText());
        conf.upDateProperty("jTextFieldSeq2", this.jTextFieldSeq2.getText());
        conf.upDateProperty("jTextFieldSeq3", this.jTextFieldSeq3.getText());
        conf.upDateProperty("jTextFieldSeq4", this.jTextFieldSeq4.getText());
        conf.upDateProperty("jTextFieldSeq5", this.jTextFieldSeq5.getText());
        conf.upDateProperty("jTextFieldSeq6", this.jTextFieldSeq6.getText());
        conf.upDateProperty("jTextFieldSeq7", this.jTextFieldSeq7.getText());
        conf.upDateProperty("jTextFieldSeq8", this.jTextFieldSeq8.getText());
        conf.upDateProperty("jTextFieldSeq9", this.jTextFieldSeq9.getText());
        conf.upDateProperty("jTextFieldSeq10", this.jTextFieldSeq10.getText());

        conf.upDateProperty("jTextFieldSystemDirSeq1", this.jTextFieldSystemDirSeq1.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq2", this.jTextFieldSystemDirSeq2.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq3", this.jTextFieldSystemDirSeq3.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq4", this.jTextFieldSystemDirSeq4.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq5", this.jTextFieldSystemDirSeq5.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq6", this.jTextFieldSystemDirSeq6.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq7", this.jTextFieldSystemDirSeq7.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq8", this.jTextFieldSystemDirSeq8.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq9", this.jTextFieldSystemDirSeq9.getText());
        conf.upDateProperty("jTextFieldSystemDirSeq10", this.jTextFieldSystemDirSeq10.getText());

        conf.storeToXML("ExecutionSys.XML", "成果物作成用の起動システム候補");
    }

    private void loadItems() {
        ConfigurationXML conf = new ConfigurationXML("ExecutionSys.XML"); //ファイルの位置は再考する

        this.jTextFieldSeq1.setText(conf.getProperty("jTextFieldSeq1"));
        this.jTextFieldSeq2.setText(conf.getProperty("jTextFieldSeq2"));
        this.jTextFieldSeq3.setText(conf.getProperty("jTextFieldSeq3"));
        this.jTextFieldSeq4.setText(conf.getProperty("jTextFieldSeq4"));
        this.jTextFieldSeq5.setText(conf.getProperty("jTextFieldSeq5"));
        this.jTextFieldSeq6.setText(conf.getProperty("jTextFieldSeq6"));
        this.jTextFieldSeq7.setText(conf.getProperty("jTextFieldSeq7"));
        this.jTextFieldSeq8.setText(conf.getProperty("jTextFieldSeq8"));
        this.jTextFieldSeq9.setText(conf.getProperty("jTextFieldSeq9"));
        this.jTextFieldSeq10.setText(conf.getProperty("jTextFieldSeq10"));

        this.jTextFieldSystemDirSeq1.setText(conf.getProperty("jTextFieldSystemDirSeq1"));
        this.jTextFieldSystemDirSeq2.setText(conf.getProperty("jTextFieldSystemDirSeq2"));
        this.jTextFieldSystemDirSeq3.setText(conf.getProperty("jTextFieldSystemDirSeq3"));
        this.jTextFieldSystemDirSeq4.setText(conf.getProperty("jTextFieldSystemDirSeq4"));
        this.jTextFieldSystemDirSeq5.setText(conf.getProperty("jTextFieldSystemDirSeq5"));
        this.jTextFieldSystemDirSeq6.setText(conf.getProperty("jTextFieldSystemDirSeq6"));
        this.jTextFieldSystemDirSeq7.setText(conf.getProperty("jTextFieldSystemDirSeq7"));
        this.jTextFieldSystemDirSeq8.setText(conf.getProperty("jTextFieldSystemDirSeq8"));
        this.jTextFieldSystemDirSeq9.setText(conf.getProperty("jTextFieldSystemDirSeq9"));
        this.jTextFieldSystemDirSeq10.setText(conf.getProperty("jTextFieldSystemDirSeq10"));

    }

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        System.out.println("Changed");
        System.out.println(jTabbedPane1.getSelectedIndex());
        if (jTabbedPane1.getSelectedIndex() == 4) { // 成果物の起動用システムのタブが選択された

        } else { // 成果物の起動用システムのタブ以外が選択されたら強制保存するべきだが方法不明
            //storeItems();
            // 上を行うと初期状態の何も表示されていないデータでファイルが上書きされてしまう。
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jPanelExeSysFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelExeSysFocusGained

    }//GEN-LAST:event_jPanelExeSysFocusGained

    private void jPanelExeSysFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelExeSysFocusLost

    }//GEN-LAST:event_jPanelExeSysFocusLost

    private void jPanelExeSysComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelExeSysComponentShown
        loadItems();
        this.isShowedSysPanel = true; // 一度でも表示されたか
    }//GEN-LAST:event_jPanelExeSysComponentShown

    private void jPanelExeSysComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelExeSysComponentHidden
        if (this.isShowedSysPanel == true) {
            storeItems(); // 一度でも表示されていればロードされている。
        }

    }//GEN-LAST:event_jPanelExeSysComponentHidden

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        storeItems();
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /*
    ここからAppInfoの設定
    
    */
    
    
    private void jButtonSysdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSysdirActionPerformed
        // 各起動アプリの実行ファイルのディレクトリを抽出
        JFileChooser filechooserAppDir = new JFileChooser();
        filechooserAppDir.setDialogTitle("自動起動するアプリの実行ファイルを選択");
        int selected = filechooserAppDir.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File fileAppDir = filechooserAppDir.getSelectedFile();
            this.jTextFieldSysdir.setText(fileAppDir.getPath());
        }
    }//GEN-LAST:event_jButtonSysdirActionPerformed

    private ResultSet selectOneRegsys(String title) { // キーひとつでの検索
        try {
            //String sql = "SELECT * FROM regsys WHERE title = " + title;
            //Connection connectionSelectOneRegsys = createConnection();
            Connection connectionSelectOneRegsys = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            PreparedStatement statement = connectionSelectOneRegsys.prepareStatement("select * from regsys where title = ?;");
            statement.setString(1, title);
            ResultSet resultSet = statement.executeQuery();

            /*
             Connection connectionSelectOneRegsys = DriverManager.getConnection(URL, USERNAME, PASSWORD);
             Statement stm = connectionSelectOneRegsys.createStatement();
             String sql_select = "select * from regsys where title = '" + title + "'";
             ResultSet resultSet = stm.executeQuery(sql_select);
             */
            resultSet.next();
            System.out.println("タイトルの索引" + resultSet.getString("title"));

            return resultSet;
        } catch (SQLException ex) {
            Logger.getLogger(ConnectionRegsys.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void updateJComboBoxItems() {
        // コネクションの作成
        try (Connection connectionUpdateJComboBoxItems = DriverManager.getConnection(URL, USERNAME, PASSWORD); //connection.setAutoCommit(false);
                PreparedStatement statement = connectionUpdateJComboBoxItems.prepareStatement("select * from regsys;");) {
            //statement.setString(1, "%");
            ResultSet resultSet = statement.executeQuery();

            this.jListTitles.removeAll();

            while (resultSet.next()) {
                String titleget = resultSet.getString("title");
                appTitlesModel.addElement(titleget);

                System.out.println("タイトル　" + titleget);
            }
            resultSet.close();

        } catch (SQLException e) {
            System.out.println("エラーが発生しました");
            JOptionPane.showMessageDialog(null, "処理中にエラーが発生しました");
            e.printStackTrace();
        }
    }

    private void jListTitlesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTitlesValueChanged
        // アイテムの選択が変更された場合の処理
        try {
            if (!this.jListTitles.getSelectedValue().toString().equals("")) { // NullPointerException が発生する。
                try {
                    // タイトルの選択が変わるに応じて内容を変化させる。
                    this.jTextFieldTitle.setText(
                            this.selectOneRegsys((this.jListTitles.getSelectedValue().toString())).getString("title")
                    );
                    this.jTextFieldSysdir.setText(
                            this.selectOneRegsys(this.jListTitles.getSelectedValue().toString()).getString("sysdir")
                    );
                    this.jTextFieldExtension.setText(
                            this.selectOneRegsys(this.jListTitles.getSelectedValue().toString()).getString("extension")
                    );
                    this.jTextAreaRemark.setText(
                            this.selectOneRegsys(this.jListTitles.getSelectedValue().toString()).getString("remark")
                    );

                } catch (SQLException ex) {
                    Logger.getLogger(ConnectionRegsys.class
                            .getName()).log(Level.SEVERE, null, ex);
                }

            }
        } catch (Exception e) {
            System.out.println("空欄");
        }
    }//GEN-LAST:event_jListTitlesValueChanged

    private void jListTitlesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListTitlesFocusGained
        // フォーカスが来たらリストを更新
        updateJComboBoxItems();
    }//GEN-LAST:event_jListTitlesFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCat1;
    private javax.swing.ButtonGroup buttonGroupCat2;
    private javax.swing.ButtonGroup buttonGroupCat3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCatDir1;
    private javax.swing.JButton jButtonCatDir2;
    private javax.swing.JButton jButtonCatDir3;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDeleteItems;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonEnterItems;
    private javax.swing.JButton jButtonEntry;
    private javax.swing.JButton jButtonIssueDir;
    private javax.swing.JButton jButtonSetDefaultItems;
    private javax.swing.JButton jButtonSourceDir;
    private javax.swing.JButton jButtonSysdir;
    private javax.swing.JButton jButtonSystemDir;
    private javax.swing.JButton jButtonSystemDirSeq1;
    private javax.swing.JButton jButtonSystemDirSeq10;
    private javax.swing.JButton jButtonSystemDirSeq2;
    private javax.swing.JButton jButtonSystemDirSeq3;
    private javax.swing.JButton jButtonSystemDirSeq4;
    private javax.swing.JButton jButtonSystemDirSeq5;
    private javax.swing.JButton jButtonSystemDirSeq6;
    private javax.swing.JButton jButtonSystemDirSeq7;
    private javax.swing.JButton jButtonSystemDirSeq8;
    private javax.swing.JButton jButtonSystemDirSeq9;
    private javax.swing.JButton jButtonSystemInvoke;
    private javax.swing.JButton jButtonWriteCat1;
    private javax.swing.JButton jButtonWriteCat2;
    private javax.swing.JButton jButtonWriteCat3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBoxNewState;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxMakeCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSeq1;
    private javax.swing.JLabel jLabelSeq10;
    private javax.swing.JLabel jLabelSeq11;
    private javax.swing.JLabel jLabelSeq12;
    private javax.swing.JLabel jLabelSeq4;
    private javax.swing.JLabel jLabelSeq5;
    private javax.swing.JLabel jLabelSeq6;
    private javax.swing.JLabel jLabelSeq7;
    private javax.swing.JLabel jLabelSeq8;
    private javax.swing.JLabel jLabelSeq9;
    private javax.swing.JList jListTitles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAppInfo;
    private javax.swing.JPanel jPanelConfig;
    private javax.swing.JPanel jPanelExeSys;
    private javax.swing.JRadioButton jRadioButtonSaveCat1Fork;
    private javax.swing.JRadioButton jRadioButtonSaveCat1Paste;
    private javax.swing.JRadioButton jRadioButtonSaveCat2Fork;
    private javax.swing.JRadioButton jRadioButtonSaveCat2Paste;
    private javax.swing.JRadioButton jRadioButtonSaveCat3Fork;
    private javax.swing.JRadioButton jRadioButtonSaveCat3Paste;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaRedirectErrorStream;
    private javax.swing.JTextArea jTextAreaRemark;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldCopyTarget1;
    private javax.swing.JTextField jTextFieldCopyTarget2;
    private javax.swing.JTextField jTextFieldCopyTarget3;
    private javax.swing.JTextField jTextFieldExtension;
    private javax.swing.JTextField jTextFieldIssueDir;
    private javax.swing.JTextField jTextFieldSeq1;
    private javax.swing.JTextField jTextFieldSeq10;
    private javax.swing.JTextField jTextFieldSeq2;
    private javax.swing.JTextField jTextFieldSeq3;
    private javax.swing.JTextField jTextFieldSeq4;
    private javax.swing.JTextField jTextFieldSeq5;
    private javax.swing.JTextField jTextFieldSeq6;
    private javax.swing.JTextField jTextFieldSeq7;
    private javax.swing.JTextField jTextFieldSeq8;
    private javax.swing.JTextField jTextFieldSeq9;
    private javax.swing.JTextField jTextFieldSourceDir;
    private javax.swing.JTextField jTextFieldSysdir;
    private javax.swing.JTextField jTextFieldSystemDir;
    private javax.swing.JTextField jTextFieldSystemDirSeq1;
    private javax.swing.JTextField jTextFieldSystemDirSeq10;
    private javax.swing.JTextField jTextFieldSystemDirSeq2;
    private javax.swing.JTextField jTextFieldSystemDirSeq3;
    private javax.swing.JTextField jTextFieldSystemDirSeq4;
    private javax.swing.JTextField jTextFieldSystemDirSeq5;
    private javax.swing.JTextField jTextFieldSystemDirSeq6;
    private javax.swing.JTextField jTextFieldSystemDirSeq7;
    private javax.swing.JTextField jTextFieldSystemDirSeq8;
    private javax.swing.JTextField jTextFieldSystemDirSeq9;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables

}
